### ISSUE TITLE
'module' object has no attribute 'CKEditorWidget'

### ISSUE THREAD

**Issue by Hiieu** [IMGIITRoorkee/django-filemanager#7]
```python
AttributeError at /admin/home/homepage/1/
'module' object has no attribute 'CKEditorWidget'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/home/homepage/1/
Django Version:	1.7
Exception Type:	AttributeError
Exception Value:	
'module' object has no attribute 'CKEditorWidget'
Exception Location:	C:\djangoproject\filemanager\models.py in formfield, line 16
```

This is models.py of app 'home' 

```python
class HomePage(models.Model):
    homecopy = CKEditorField(filemanager_url='/app/abc/')
    class Meta:
        verbose_name=verbose_name_plural="1. Main Page"
    def __unicode__(self):
        return 'Main Page'
```

When I change 
`from filemanager.models import CKEditorField` 
to
`from filemanager.widgets import CKEditorWidget`

I have no errors, but CKEditor dissapears and I don't even have any text areas in my django admin panel.

Views of my djangoproject urls.py

```python
urlpatterns = patterns('',
    url(r'^abc/'+path_end,'view'),
    url(r'^$','home.views.index'),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

```

**Comment by Hiieu** [comment]
Views of my djangoproject urls.py

```python
urlpatterns = patterns('',
    url(r'^abc/'+path_end,'view'),
    url(r'^$','home.views.index'),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

```

**Comment by sjiitr** [comment]
Thank you @Hiieu for showcasing error. The error has been fixed with commit 57297.

Still CKEditor widget wouldn't be visible in admin panel. For that you'll have to add this code to `admin.py` file of `home` app too.

<pre>
from django.contrib import admin
from django.db import models
from home.models import HomePage
from filemanager.widgets import CKEditorWidget

class HomePageAdmin(admin.ModelAdmin):
  formfield_overrides = {
    models.TextField: {'widget': CKEditorWidget(config={'toolbar':'Standard'})},
  }

admin.site.register(HomePage, HomePageAdmin)
</pre>

Change parameters in `config` argument to configure how CKEditor is shown. Some parameters are
`toolbar` = `'Basic'/'Standard'/'Full'`
`width` = integer
`height` = integer

This extra argument `config` can also be supplied with CKEditorField if your form automatically infers the widget from the field.
